# Generated by Django 4.2.6 on 2023-10-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('lecturer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendace', to='lecturer.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendace', to='users.student')),
            ],
        ),
    ]
