# Generated by Django 4.2.6 on 2023-10-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0004_lecture_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
